### PR TITLE
Adding a Github Actions workflow to run Jekyll build

### PR DESCRIPTION
**Pull request by ddaws**
This allows us to confirm that changes submitted to the site do not break the Jekyll build. I am not too familiar with Jekyll (looks simple enough) but this helps me feel more confident submitting changes in the future. 

Next up will be adding some CI for linting and some small changes. I would like to work my way up to fixing the menu on mobile

### CODE REVIEW

**Comment by ddaws** [comment]
Here is an example of a breaking change
https://github.com/ddaws/gutenbergsite/pull/1

And here is an example of a non-breaking change
https://github.com/ddaws/gutenbergsite/pull/2

**Comment by eshellman** [comment]
Looks good to me. @gbnewby

**Comment by gbnewby** [comment]
Agreed - would you go ahead to merge into main? I'm not confident I know
how to do that correctly.

**Comment by gbnewby** [comment]
I pulled to the live website and regenerated with jekyll.

I didn't see any visible changes, and no errors were generated - as
expected. So, this looks like it worked as intended.

Thanks for this submission, Dawson.

Dr. Gregory B. Newby
Chief Executive and Director
Project Gutenberg Literary Archive Foundation www.gutenberg.org
A 501(c)(3) not-for-profit organization with EIN 64-6221541]

**Comment by ddaws** [comment]
I'm happy to contribute, and I hope to make more significant changes in the future 🙂

**Pull request merged**
